name: Deploy to Firethree Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_NODE_ENV: 'production'
          file_name: .env.production
          dotfiles: true
          concurrency: 5

      - name: Install Packages
        run: yarn

      - name: Build page
        run: yarn build

      - uses:
